server:
  port: 8761  # default Eureka server port

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false   # server doesn’t register itself
    fetch-registry: false         # server doesn’t fetch registry
