spring:
  application:
    name: user-service
  config:
    import: "optional:configserver:http://user:12345@localhost:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 10000
        max-attempts: 10
        multiplier: 1.5
      profile: default
      label: main
      discovery:
        enabled: false
